#for documentation see project at https://github.com/Dilbert66/esphome-dsckeybus
substitutions:
  name: "dscalarm" #unique network name
  friendlyName: "DSC Alarm" #friendly name for this device
  panelId: DSCAlarm  #used as the service variable name.
  
dsc_alarm_panel:
  id: $panelId
  #you can enter a list of user codes mapped to their names for display in armed/disarmed event messages
  usercodes: "1:John,2:Sally,3:Bob" #
  
  #Only comes into effect if a password prompt occurs when arming eg. night mode
  accesscode: !secret access_code 
  
  #used to select the default partition associated with the alarm panel messages
  defaultpartition: "1" 
  
  maxzones: "64" # maximum amount of zones your system supports
  
  # dsc debug level: 0 = off, 1 = minimal, 2 = all packets shown on console  3 =  + serial port debugging
  dscdebuglevel: "2"  
   
  #zone expander addresses:
  # 9  - zones 9-16
  # 10 - zones 17-24
  # 11 - zones 25-32
  # 12 - zones 33-40 (for systems with 64 zone support)
  # 13 - zones 41-48 (for systems with 64 zone support)
  # 14 - zones 49-56 (for systems with 64 zone support)
  # 16 - zones 57-64 (for systems with 64 zone support)  
  expanderaddr1: "0" # 1st zone expander emulator address to use . Set to 0 to disable. 
  expanderaddr2: "0" # 2nd expander emulator address to use . Set to 0 to disable. 

  ##ESP32 Pins
  #dscclockpin: "22"
  #dscreadpin: "21"
  #dscwritepin: "18"
  
  ##ESP8266 Pins
  #dscclockpin: "5"
  #dscreadpin: "4"
  #dscwritepin: "15" 
  #dscclockpin: "D1"
  #dscreadpin: "D2"
  #dscwritepin: "D8"  
  dscclockpin: "5"
  dscreadpin: "4"
  dscwritepin: "15"  

  clean_build: "false" #default is false.  set to true if getting duplication errors in linking step.  

#esp32: 
#  board: nodemcu-32s
#  framework: 
#    type: arduino
#    version: recommended

esp8266:    
  board: d1_mini_lite  
  framework: 
    version: recommended

#esp8266:    
  #board: nodemcuv2
  #framework:
    #version: recommended 

#location of alarm panel code.  You can use the github release version  or 
#copy the code to directory "my_components" in your main esphome directory   
# see here for more info: https://esphome.io/components/external_components       
external_components:
  - source: github://Dilbert66/esphome-components@main #uncomment to use github repository
  #- source:  my_components #uncomment to use local directory 
    components: [dsc_alarm_panel,binary_sensor,text_sensor] 
    refresh: 10min
  
esphome:
  name: $name
  friendly_name: $friendlyName

#output sympols to output.map for debugging. You can remove if not needed
  platformio_options:
    build_flags: 
        - "-Wl,-Map,output.map"  

#you can remove/disable this section if you don't want your panel time updated automatically  
interval:
  - interval: 7200s
    then:
      - lambda: |-
          $panelId->set_panel_time();
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: "$name"
    password: !secret wifi_password

logger:
  baud_rate: 115200
  level: DEBUG

#api:
#   encryption:
#    key: !secret encryption_key    
    
#to use mqtt disable the api: section above. This enables you to use esphome with 
#non homeassistant systems
#modify the mqtt section to your needs
#See: https://esphome.io/components/mqtt.html

#mqtt:
  #broker: 192.168.2.175
  #port: 1883
  #username: mqttuser
  #password: mqttuser
  #discovery_prefix: "homeassistant"
  #topic_prefix: $name
mqtt:
  broker: 192.168.8.123 #your mqtt broker address
  port: 1883  
  username: !secret mqtt_username #your mqtt user name
  password: !secret mqtt_password #your mqtt user pass  
  discovery_prefix: "homeassistant"
  topic_prefix: $name

ota:
   platform: esphome
   password: !secret ota_password
#   safe_mode: True
   on_begin:
       switch.turn_off: connection_status_switch   
   
time:
 - platform: sntp


################################################################################
# Edit binary and text sensors below to suit your alarm setup. 
# The id code is entered using the "id_code:" tag.  Alternatively you can
# add the id code in round brackets  at the end of the sensor name: eg. (z1)
# You can safely add or remove any sensors as needed.

binary_sensor:
### zone setup ###
# zone status open/close for each zone 
# zone id code = z+zone number  
  - platform: gpio
    name: "Postbox entry"
    device_class: door    
    pin: 
      number: D5
      #inverted: false    
      mode:
        input: true
        pullup: false      
    filters:
      - delayed_on: 50ms

  - platform: gpio
    name: "Postbox door"
    device_class: door    
    pin: 
      number: D6
      #inverted: false
      mode:
        input: true
        pullup: false          
    filters:
      - delayed_on: 50ms

  - platform: gpio
    name: "Door spajz"
    device_class: door    
    pin: 
      number: D7
      #inverted: false
      mode:
        input: true
        pullup: false          
    filters:
      - delayed_on: 50ms
      

    #zone status open/close for each zone 
  - platform: template
    id: z1
    name: "Gate bell"
    device_class: sound
    publish_initial_state: true        

  - platform: template
    id: z2
    name: "Door gate"
    device_class: door
    publish_initial_state: true        

  - platform: template
    id: z3
    name: "Door shed"
    device_class: door    
    publish_initial_state: true        

  - platform: template
    id: z4
    name: "Motion spajz"
    device_class: motion
    publish_initial_state: true        

  - platform: template
    id: z5
    name: "Motion kitchen"
    device_class: motion
    publish_initial_state: true        

  - platform: template
    id: z7
    name: "Motion lobby"
    device_class: motion
    publish_initial_state: true        

  - platform: template
    id: z9
    name: "Smoke bathroom"
    device_class: smoke
    publish_initial_state: true        

  - platform: template
    id: z10
    name: "Motion THK"
    device_class: motion
    publish_initial_state: true        

  - platform: template
    id: z11
    name: "Motion kitchensink"
    device_class: motion
    publish_initial_state: true        

  - platform: template
    id: z12
    name: "Motion WC"
    device_class: motion
    publish_initial_state: true        

  - platform: template
    id: z13
    name: "Smoke THK"
    device_class: smoke
    publish_initial_state: true        

  - platform: template
    id: z14
    name: "Smoke livingroom"
    device_class: smoke
    publish_initial_state: true        

  - platform: template
    id: z15
    name: "Smoke spajz"
    device_class: smoke
    publish_initial_state: true        

  - platform: template
    id: z16
    name: "Raining"
    device_class: moisture
    publish_initial_state: true        

  - platform: template
    id: z17
    name: "Door outside"
    device_class: door
    publish_initial_state: true        

  - platform: template
    id: z18
    name: "Door entrance"
    device_class: door
    publish_initial_state: true        

  - platform: template
    id: z19
    name: "Motion nappali"
    device_class: motion
    publish_initial_state: true        

  - platform: template
    id: z20
    name: "Motion nappali2"
    device_class: motion
    publish_initial_state: true        

  - platform: template
    id: z21
    name: "Motion Panka"
    device_class: motion
    publish_initial_state: true        

  - platform: template
    id: z22
    name: "Smoke Panka"
    device_class: smoke
    publish_initial_state: true        

  - platform: template
    id: z23
    name: "Motion bedroom"
    device_class: motion
    publish_initial_state: true        

  - platform: template
    id: z24
    name: "Smoke bedroom"
    device_class: smoke   
    publish_initial_state: true        

  - platform: template
    id: z25
    name: "Workshop door"
    device_class: door    
    publish_initial_state: true        

  - platform: template
    id: z26
    name: "Garage door Panka"
    device_class: garage_door    
    publish_initial_state: true        

  - platform: template
    id: z27
    name: "Garage door THK"
    device_class: garage_door    
    publish_initial_state: true        

  - platform: template
    id: z28
    name: "Motion garage 1"
    device_class: motion
    publish_initial_state: true        

  - platform: template
    id: z29
    name: "Motion garage 2"
    device_class: motion
    publish_initial_state: true        

  - platform: template
    id: z30
    name: "Smoke garage"
    device_class: smoke    
    publish_initial_state: true        
    
  - platform: template
    id_code: rdy_1  
    name: "Partition 1 Ready (rdy_1)"
    publish_initial_state: true     

  - platform: template
    id: arm_1
    name: "Partition 1 Armed (arm_1)"
    publish_initial_state: true     
    
  - platform: template
    id: rdy_2
    name: "Partition 2 Ready (rdy_2)" 
    publish_initial_state: true     

  - platform: template
    id: arm_2
    name: "Partition 2 Armed (arm_2)"     
    publish_initial_state: true     

    #panel trouble status on/off
  - platform: template
    id: tr
    name: "Trouble Status (tr)"
    device_class: problem
    publish_initial_state: true     

    #battery status ok/low
  - platform: template
    id: bat
    name: "Battery Status (bat)"
    device_class: problem
    publish_initial_state: true     

    #AC power status ok/no power
  - platform: template
    id: ac
    name: "AC Status (ac)"
    device_class: plug
    publish_initial_state: true     

# partition fire alarm indicators
# fire id code = fa_ + partition number  
  - platform: template
    id_code: fa_1  
    device_class: smoke
    name: "Fire partition 1 Status (fa_1)"
    publish_initial_state: true        
    
  - platform: template
    id_code: fa_2  
    device_class: smoke
    name: "Fire partition 2 Status (fa_2)"  
    publish_initial_state: true          

# partition in alarm indicators
# alarm id code = al_ + partition number  
  - platform: template
    id_code: al_1  
    name: "partition 1 Alarm Status (al_1)"
    publish_initial_state: true        
    
  - platform: template
    id_code: al_2  
    name: "partition 2 Alarm Status (al_2)"  
    publish_initial_state: true        

# relay PGM channels. Will show the state of the activate relay channel on/off
# relay id code = r + channel number
  - platform: template
    id_code: r1  
    name: "PGM 1 (r1)"
    publish_initial_state: true        

  - platform: template
    id_code: r2  
    name: "PGM 2 (r2)"
    publish_initial_state: true        

  - platform: template
    id_code: r3  
    name: "PGM 3 (r3)"
    publish_initial_state: true        

  - platform: template
    id_code: r4  
    name: "PGM 4 (r4)"
    publish_initial_state: true              

text_sensor:
# general system status online/disconnected 
# system status id code = ss
  - platform: template
    id_code: ss  
    name: "System Status (ss)"
    icon: "mdi:shield"

# battery level status for wireless channels, tamper , in alarm, etc for individual zones
# zone status id code = zs    
  - platform: template
    id_code: zs  
    name: "zone status (zs)"
    icon: "mdi:shield"  

# partition status ie ready/not ready, triggered, etc
# partition status id code = ps_ + partition number   
  - platform: template
    id_code: ps_1  
    name: "Partition 1 Status (ps_1)"
    icon: "mdi:shield"

  - platform: template
    id_code: ps_2  
    name: "Partition 2 Status (ps_2)" 
    icon: "mdi:shield"  

# more verbose message regarding the partition status. ie zones open, bypassed, etc
# partition message id code = msg_ + partition number    
  - platform: template
    id_code: msg_1  
    name: "Partition 1 Msg (msg_1)"
    icon: "mdi:alert-box"

  - platform: template
    id_code: msg_2  
    name: "Partition 2 Msg (msg_2)"
    icon: "mdi:alert-box"

# virtual lcd keypad line1 and line2 messages for each partition   
# partition line1 id code = ln1_ + partition number
# partition line2 id code = ln2_ + partition number
# partition 1
  - platform: template
    id_code: ln1_1  
    name: "line1 Partition 1 (ln1_1)"
    icon: "mdi:alert-box"

  - platform: template
    id_code: ln2_1  
    name: "line2 Partition 1 (ln2_1)"
    icon: "mdi:alert-box"  

# partition 2
  - platform: template
    id_code: ln1_2  
    name: "line1 partition 2 (ln1_2)"
    icon: "mdi:alert-box"

  - platform: template
    id_code: ln2_2  
    name: "line2 partition 2 (ln2_2)"
    icon: "mdi:alert-box" 

# generic event messages from panel
# panel event id code = evt
  - platform: template
    id_code: evt  
    name: "event (evt)"
    icon: "mdi:alert-box" 
  
# partition beeps
# beeps id code = bp_ + partition number
  - platform: template
    id_code: bp_1  
    name: "beeps (bp_1)"
    icon: "mdi:alert-box" 

  - platform: template
    id_code: bp_2  
    name: "partition 2 beeps (bp_2)"
    icon: "mdi:alert-box"   

 # panel trouble messages  
 # panel msg id code = tr_msg
  - platform: template
    id_code: tr_msg  
    name: "Trouble Msg (tr_msg)" 
    icon: "mdi:alert-box"

# this sensor below is optional - example use of pin d8 as a zone trigger pin for the emulated zone expander  
# this emulates the hardware connection for a pc5108 board. Use a pull down/pull up resistor.  Adjust logic accordingly for the correct logic output. ie invert
 # - platform: gpio  
 #   pin: D8
 #   device_class: window
 #   on_press:       #pin high=on(open), pin low=off(closed)
 #     - lambda: |-
 #         dsc.setZoneFault(17,1);  #set zone 17 as open
 #   on_release:
 #     - lambda: |-
 #         dsc.setZoneFault(17,0);  #set zone 17 as closed
 


 # end of panel sensor setup - no need to edit anything below.
##########################################################################################
switch:
    #shows status of connection status to panel.  You can disconnect before upload using the switch.
  - platform: template
    name: "Connection"
    id: connection_status_switch
    lambda: |-
      return dsc.keybusConnected;
    icon: "mdi:shield-link-variant"
    turn_on_action:
      - switch.toggle: restart_switch
    turn_off_action:
      - lambda: |-
          disconnectKeybus();

  - platform: restart
    id: restart_switch
    
  - platform: safe_mode
    name: "Safe Mode" 
